version: 0.2

env:
  variables:
    CLUSTER_NAME: my-eks-cluster

phases:
  install:
    commands:
      - echo "Installing required tools..."
      - aws --version
      - docker --version

      # Install Trivy for secret scanning
      - echo "Installing Trivy..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - sudo mv ./bin/trivy /usr/local/bin/trivy

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # -------------------------------
      # 🔐 SECRET SCAN (FAIL IF FOUND)
      # -------------------------------
      - echo "Scanning repository for secrets..."
      - trivy fs --scanners secret --exit-code 1 .

      - export BACKEND_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/todo-backend:latest
      - export FRONTEND_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/todo-frontend:latest
      - export NGINX_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/todo-nginx:latest

  build:
    commands:
      - echo "Building Docker images..."

      - docker build -t todo-backend ./backend
      - docker tag todo-backend:latest $BACKEND_IMAGE

      - docker build -t todo-frontend ./frontend
      - docker tag todo-frontend:latest $FRONTEND_IMAGE

      - docker build -t todo-nginx ./nginx
      - docker tag todo-nginx:latest $NGINX_IMAGE

  post_build:
    commands:
      - echo "Pushing Docker images to ECR..."
      - docker push $BACKEND_IMAGE
      - docker push $FRONTEND_IMAGE
      - docker push $NGINX_IMAGE

      - echo "Deploying to EKS..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - kubectl apply -f k8s/
      - kubectl rollout restart deployment todo-backend
      - kubectl rollout restart deployment todo-frontend
      - kubectl rollout restart deployment todo-nginx
version: 0.2

env:
  variables:
    CLUSTER_NAME: my-eks-cluster

phases:
  install:
    commands:
      - echo "Installing required tools"
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - export BACKEND_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/todo-backend:latest
      - export FRONTEND_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/todo-frontend:latest
      - export NGINX_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/todo-nginx:latest

  build:
    commands:
      - echo "Building Docker images"

      - docker build -t todo-backend ./backend
      - docker tag todo-backend:latest $BACKEND_IMAGE

      - docker build -t todo-frontend ./frontend
      - docker tag todo-frontend:latest $FRONTEND_IMAGE

      - docker build -t todo-nginx ./nginx
      - docker tag todo-nginx:latest $NGINX_IMAGE

  post_build:
    commands:
      - echo "Pushing Docker images to ECR"

      - docker push $BACKEND_IMAGE
      - docker push $FRONTEND_IMAGE
      - docker push $NGINX_IMAGE

      - echo "Deploying to EKS"
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - kubectl apply -f k8/
      - kubectl rollout restart deployment todo-backend
      - kubectl rollout restart deployment todo-frontend
      - kubectl rollout restart deployment todo-nginx
