version: 0.2

env:
  variables:
    AWS_REGION: eu-north-1
    AWS_ACCOUNT_ID: 985414871677
    EKS_CLUSTER: my-eks-cluster
    
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Build backend image
      - docker build -t backend ./backend
      - docker tag backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend:latest

      - echo Build frontend image
      - docker build -t frontend ./frontend
      - docker tag frontend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest

      - echo Build nginx image
      - docker build -t nginx ./nginx
      - docker tag nginx:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nginx:latest

  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nginx:latest

      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER
      - kubectl apply -f k8/
