apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: default
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/tododb?sslmode=disable"
