apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-nginx
  template:
    metadata:
      labels:
        app: todo-nginx
    spec:
      containers:
      - name: nginx
        image: NGINX_IMAGE_PLACEHOLDER
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/nginx.conf
              subPath: nginx.conf

      # ✅ ADD THIS PART (volumes)
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: todo-nginx
