# sonarqube-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc
spec:
  storageClassName: gp3-wffc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
